# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --configuration production
  displayName: 'npm install and build'

- powershell: |
    Get-ChildItem -Path 'Insert root path' -recurse
  displayName: 'folder structure'

# - task: ArchiveFiles@2
#   inputs:
#     rootFolderOrFile: '$(Build.BinariesDirectory)'
#     includeRootFolder: true
#     archiveType: 'zip'
#     archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
#     replaceExistingArchive: true
# - task: AzureWebApp@1
#   inputs:
#     azureSubscription: 'Azure subscription 1(c9ea8d65-e554-42b9-a500-7bc949e15c32)'
#     appType: 'webAppLinux'
#     appName: 'amit-goldshtein-cv'
#     package: '$(System.DefaultWorkingDirectory)/**/*.zip'
#     runtimeStack: 'NODE|16-lts'