# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --configuration production
  displayName: 'npm install and build'



- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/dist/portfolio'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
# - task: AzureWebApp@1
#   inputs:
#     azureSubscription: 'Azure subscription 1(c9ea8d65-e554-42b9-a500-7bc949e15c32)'
#     appType: 'webAppLinux'
#     appName: 'amit-goldshtein-cv'
#     package: '$(Build.ArtifactStagingDirectory)/*.zip'
#     runtimeStack: 'NODE|16-lts'

- script: |
      echo "Structure of work folder of this pipeline:"
      tree $(Agent.WorkFolder)/1
      echo "Build.ArtifactStagingDirectory:" 
      echo "$(Build.ArtifactStagingDirectory)"
      echo "Build.BinariesDirectory:" 
      echo "$(Build.BinariesDirectory)"
      echo "Build.SourcesDirectory:"
      echo "$(Build.SourcesDirectory)"
  displayName: 'folder structure'